CREATE TABLE IF NOT EXISTS demo_alltypes (
  A_BYTE BYTE,
  A_BOOL BOOLEAN,
  A_SHORT SHORT,
  A_INTEGER INTEGER,
  A_LONG LONG,
  A_DOUBLE DOUBLE,
  A_STRING STRING,
  A_TS TIMESTAMP,
  A_IP IP
);

INSERT INTO demo_alltypes (A_BYTE,A_BOOL,A_SHORT,A_INTEGER,A_LONG,A_DOUBLE,A_STRING,A_TS,A_IP)
  VALUES ('1','TRUE','1','1','1','1.1','VALUE 1',current_timestamp,'127.0.0.1');
INSERT INTO demo_alltypes (A_BYTE,A_BOOL,A_SHORT,A_INTEGER,A_LONG,A_DOUBLE,A_STRING,A_TS,A_IP)
  VALUES ('2','TRUE','2','2','2','2.1','VALUE 2',current_timestamp,'127.0.0.2');
INSERT INTO demo_alltypes (A_BYTE,A_BOOL,A_SHORT,A_INTEGER,A_LONG,A_DOUBLE,A_STRING,A_TS,A_IP)
  VALUES ('3','TRUE','3','3','3','3.1','VALUE 3',current_timestamp,'127.0.0.3');
INSERT INTO demo_alltypes (A_BYTE,A_BOOL,A_SHORT,A_INTEGER,A_LONG,A_DOUBLE,A_STRING,A_TS,A_IP)
  VALUES ('4','TRUE','4','4','4','4.1','VALUE 4',current_timestamp,'127.0.0.4');
